IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'MovimentosDB')
BEGIN
    CREATE DATABASE MovimentosDB;
END
GO
USE MovimentosDB;
GO

CREATE TABLE PRODUTO (
    COD_PRODUTO CHAR(4) PRIMARY KEY,
    DES_PRODUTO VARCHAR(30) NULL,
    STA_STATUS CHAR(1) NULL
);

CREATE TABLE PRODUTO_COSIF (
    COD_PRODUTO CHAR(4) NOT NULL,
    COD_COSIF CHAR(11) NOT NULL,
    COD_CLASSIFICACAO CHAR(6) NULL,
    STA_STATUS CHAR(1) NULL,
    PRIMARY KEY (COD_PRODUTO, COD_COSIF),
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);

CREATE TABLE MOVIMENTO_MANUAL (
    DAT_MES NUMERIC(2, 0) NOT NULL,
    DAT_ANO NUMERIC(4, 0) NOT NULL,
    NUM_LANCAMENTO NUMERIC(18, 0) NOT NULL,
    COD_PRODUTO CHAR(4) NOT NULL,
    COD_COSIF CHAR(11) NOT NULL,
    DES_DESCRICAO VARCHAR(50) NULL,
    DAT_MOVIMENTO SMALLDATETIME NOT NULL,
    COD_USUARIO VARCHAR(15) NOT NULL,
    VAL_VALOR NUMERIC(18, 2) NOT NULL,
    PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO),
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF(COD_PRODUTO, COD_COSIF)
);

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P001', 'Produto 1', 'A');
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P002', 'Produto 2', 'A');
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) 
VALUES ('P001', 'COSIF001', 'CLS001', 'A');
INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) 
VALUES ('P002', 'COSIF002', 'CLS002', 'A');

INSERT INTO MOVIMENTO_MANUAL (
    DAT_MES, DAT_ANO, NUM_LANCAMENTO, 
    COD_PRODUTO, COD_COSIF, DES_DESCRICAO, 
    DAT_MOVIMENTO, COD_USUARIO, VAL_VALOR
)
VALUES
(7, 2025, 1, 'P001', 'COSIF001', 'Teste 1', GETDATE(), 'admin', 100.00),
(7, 2025, 2, 'P001', 'COSIF001', 'Teste 2', GETDATE(), 'admin', 200.00),
(7, 2025, 3, 'P001', 'COSIF001', 'Teste 3', GETDATE(), 'admin', 300.00),
(7, 2025, 4, 'P001', 'COSIF001', 'Teste 4', GETDATE(), 'admin', 400.00),
(7, 2025, 5, 'P001', 'COSIF001', 'Teste 5', GETDATE(), 'admin', 500.00);
GO

INSERT INTO MOVIMENTO_MANUAL (
    DAT_MES, DAT_ANO, NUM_LANCAMENTO, 
    COD_PRODUTO, COD_COSIF, DES_DESCRICAO, 
    DAT_MOVIMENTO, COD_USUARIO, VAL_VALOR
)
VALUES
(8, 2025, 1, 'P001', 'COSIF001', 'Teste 1', GETDATE(), 'admin', 100.00),
(8, 2025, 2, 'P001', 'COSIF001', 'Teste 2', GETDATE(), 'admin', 200.00),
(8, 2025, 3, 'P001', 'COSIF001', 'Teste 3', GETDATE(), 'admin', 300.00),
(8, 2025, 4, 'P001', 'COSIF001', 'Teste 4', GETDATE(), 'admin', 400.00),
(8, 2025, 5, 'P001', 'COSIF001', 'Teste 5', GETDATE(), 'admin', 500.00);
GO
