// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovimentosManual.Infrastructure.Context;

#nullable disable

namespace MovimentosManual.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MovimentosDbContext))]
    partial class MovimentosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovimentosManual.Domain.Entities.Cosif", b =>
                {
                    b.Property<string>("CodigoCosif")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("COD_COSIF");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DES_COSIF");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("CodigoCosif");

                    b.ToTable("COSIF", "dbo");
                });

            modelBuilder.Entity("MovimentosManual.Domain.Entities.MovimentoManual", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("CodigoCosif")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("COD_COSIF");

                    b.Property<int>("NumeroLancamento")
                        .HasColumnType("int")
                        .HasColumnName("NUM_LANCAMENTO");

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("DAT_ANO");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("DAT_MES");

                    b.Property<string>("CodigoUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("COD_USUARIO");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DAT_MOVIMENTO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DES_DESCRICAO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VAL_VALOR");

                    b.HasKey("CodigoProduto", "CodigoCosif", "NumeroLancamento", "Ano", "Mes");

                    b.HasIndex("CodigoCosif");

                    b.ToTable("MOVIMENTO_MANUAL", "dbo");
                });

            modelBuilder.Entity("MovimentosManual.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DES_PRODUTO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("CodigoProduto");

                    b.ToTable("PRODUTO", "dbo");
                });

            modelBuilder.Entity("MovimentosManual.Domain.Entities.ProdutoCosif", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("COD_PRODUTO");

                    b.Property<string>("CodigoCosif")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("COD_COSIF");

                    b.Property<string>("CodigoClassificacao")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("COD_CLASSIFICACAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("STA_STATUS");

                    b.HasKey("CodigoProduto", "CodigoCosif");

                    b.HasIndex("CodigoCosif");

                    b.ToTable("PRODUTO_COSIF", "dbo");
                });

            modelBuilder.Entity("MovimentosManual.Domain.Entities.MovimentoManual", b =>
                {
                    b.HasOne("MovimentosManual.Domain.Entities.Cosif", "Cosif")
                        .WithMany("Movimentos")
                        .HasForeignKey("CodigoCosif")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovimentosManual.Domain.Entities.Produto", "Produto")
                        .WithMany("Movimentos")
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cosif");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("MovimentosManual.Domain.Entities.ProdutoCosif", b =>
                {
                    b.HasOne("MovimentosManual.Domain.Entities.Cosif", "Cosif")
                        .WithMany("ProdutosCosif")
                        .HasForeignKey("CodigoCosif")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovimentosManual.Domain.Entities.Produto", "Produto")
                        .WithMany("ProdutosCosif")
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cosif");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("MovimentosManual.Domain.Entities.Cosif", b =>
                {
                    b.Navigation("Movimentos");

                    b.Navigation("ProdutosCosif");
                });

            modelBuilder.Entity("MovimentosManual.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Movimentos");

                    b.Navigation("ProdutosCosif");
                });
#pragma warning restore 612, 618
        }
    }
}
